export const adminSettingsMenu = [
  {
    id: 1,
    name: 'Provider App Settings',
    data: [
      {
        id: 1,
        title: 'Test (Quiz)',
        subTitle: 'Manage test questions for different categories. ',
        navigate: '/settings/',
      },
      {
        id: 2,
        title: 'Skills Checklist',
        subTitle: 'Manage skills for different categories. ',
        navigate: '/settings/',
      },
      {
        id: 3,
        title: 'Shift Cancel/Rejected Reasons',
        subTitle: 'Manage default reasons for cancel shifts. This will be shown when cancelling a Shift.',
        navigate: '/settings/',
      },
      {
        id: 4,
        title: 'Gamification',
        subTitle: 'Manage and edit required metrics for each badge level.',
        navigate: '/settings/',
      },
      {
        id: 5,
        title: 'Attendance Score',
        subTitle: 'Manage attendance score parameters and categories.',
        navigate: '/settings/',
      },
      {
        id: 6,
        title: 'Provider Profile',
        subTitle: 'Manage required fields for provider profile.',
        navigate: '/settings/',
      },
      {
        id: 7,
        title: 'Schedule and Request',
        subTitle: 'Schedule permissions and parameters.',
        navigate: '/settings/',
      },
      {
        id: 8,
        title: 'Time Entry Approval',
        subTitle: 'Settings related to time entry approval',
        navigate: '/settings/',
      },
      {
        id: 9,
        title: 'General Settings',
        subTitle: 'Settings related to general activities',
        navigate: '/settings/',
      },
    ],
  },
  {
    id: 2,
    name: 'Facility Portal Settings',
    data: [
      {
        id: 1,
        title: 'General',
        subTitle: 'Choose what to show or not from different modules of facility portal.',
        navigate: '/settings/',
      },
      {
        id: 2,
        title: 'Shifts',
        subTitle: 'Manage shift timings & cancellation reasons.',
        navigate: '/settings/',
      },
      {
        id: 3,
        title: 'Provider',
        subTitle: 'Manage Provider status and DNR Reasons.',
        navigate: '/settings/',
      },
      {
        id: 4,
        title: 'Time and Attendance',
        subTitle: 'Manage Reject Timecard Reasons',
        navigate: '/settings/',
      },
      {
        id: 5,
        title: 'Billing Payment Methods',
        subTitle: 'Manage payment methods, add new or remove.',
        navigate: '/settings/',
      },
      {
        id: 6,
        title: 'Facility Contact Permissions',
        subTitle: 'Show or hide permissions for facility contact permissions dropdown.',
        navigate: '/settings/',
      },
      {
        id: 7,
        title: 'My facility',
        subTitle: 'Schedule permissions and parameters.',
        navigate: '/settings/',
      },
      {
        id: 8,
        title: 'Document Categories',
        subTitle: 'Add, delete and manage document categories.',
        navigate: '/settings/',
      },
      {
        id: 9,
        title: 'Line of Business',
        subTitle: 'Add, delete and manage document categories.',
        navigate: '/settings/',
      },
    ],
  },
  {
    id: 3,
    name: 'Admin Portal Settings',
    data: [
      {
        id: 1,
        title: 'Certification',
        subTitle: 'Manage default reasons for cancel shifts. This will be shown when cancelling a Shift.',
        navigate: '/settings/certification',
      },
      {
        id: 2,
        title: 'Specialties',
        subTitle: 'Manage skills for different categories. ',
        navigate: '/settings/specialties',
      },
      {
        id: 3,
        title: 'Shift Type',
        subTitle: 'Manage and edit required metrics for each badge level.',
        navigate: '/settings/',
      },
      {
        id: 4,
        title: 'Note Type',
        subTitle: 'Manage attendance score parameters and categories.',
        navigate: '/settings/',
      },
      {
        id: 5,
        title: 'Provider Rejection Reasons',
        subTitle: 'Manage attendance score parameters and categories.',
        navigate: '/settings/',
      },
      {
        id: 6,
        title: 'Facility Rejection Reasons',
        subTitle: 'Manage attendance score parameters and categories.',
        navigate: '/settings/',
      },
      {
        id: 7,
        title: 'Evaluation Designer',
        subTitle: 'Add, delete and manage document categories.',
        navigate: '/settings/',
      },
      {
        id: 8,
        title: 'Document Categories',
        subTitle: 'Schedule permissions and parameters.',
        navigate: '/settings/',
      },
      {
        id: 9,
        title: 'Workers Comp Code',
        subTitle: 'Manage preferences for provider app.',
        navigate: '/settings/',
      },
      {
        id: 10,
        title: 'Languages',
        subTitle: 'Settings related to time entry approval',
        navigate: '/settings/',
      },
      {
        id: 11,
        title: 'Status Option',
        subTitle: 'Settings related to general activities',
        navigate: '/settings/',
      },
      {
        id: 12,
        title: 'Notification Settings',
        subTitle: 'Settings related to general activities',
        navigate: '/settings/',
      },
      {
        id: 13,
        title: 'Compliance Manager',
        subTitle: 'Settings related to general activities',
        navigate: '/settings/',
      },
      {
        id: 14,
        title: 'Admin Contacts',
        subTitle: 'Settings related to general activities',
        navigate: '/settings/admin-contacts',
      },
    ],
  },
]
