export const VALIDATION_ERROR = {
  COMMON: {
    PASSWORD: 'Please input your password!',
    EMAIL: 'Enter Email Address',
    EMAIL2: 'Enter valid email address',
    USERNAME: 'Enter username',
    USERNAME2: 'Username can only contain letters, numbers, and underscores',
    MOBILE: 'Enter mobile number',
    MOBILE2: 'Mobile can only contain number',
    MINNUMBER: 'Must be at least 8 characters',
    MAXNUMBER: 'Cannot exceed 14 characters',
    NAME: 'Enter a name',
    NAME2: 'Name can only contain letters, hyphens, apostrophes, and spaces',
    ROLE: 'Please enter a role',
    DESCRIPTION: 'Please enter description',
    ROLESUBMIT: 'Please enter both a role name and a description for the new role.',
    COUNTRY_CODE: 'Please select!',
    ROLE_DROPDOWN: 'Please select a role',
    BANK_AC: 'Please select bank account',
    SOURCE_NAME: 'Enter a source name',
    TESTNAME: 'Enter a test name',
    CERTIFICATION: 'Please select a certificate',
    REQUIREDTOPASS: 'Please select passing score',
    DURATION: 'Please select test time',
    CHCKLISTNAME: 'Enter a checklist name',
  },
  IMAGE: {
    ONLYIMG: 'Only image files are allowed for upload.',
    FAILDUPLOAD: 'Failed to upload image. Please try again.',
  },
  PASSWORD: {
    EMPTY_CURRENT_PASSWORD: 'Please input your current password!',
    EMPTY_CONFIRM_PASSWORD: 'Please input your confirm password!',
    EMPTY_NEW_PASSWORD: 'Please input your new password!',
    NOT_MATCH_PASSWORD: 'The passwords that you entered do not match.',
    MINIMUM_LENGTH: 'Password minimum 8 characters long',
    INVALID_PASSWORD: 'Include at least one number, one special character, one uppercase letter, and one lowercase letter.',
  },
  CERTI_NAME: 'Enter a certificate name',
  CERTI_ABB: 'Enter a abbreviation',
  SPECIALITY_NAME: 'Enter a specialty name',
  DROPDOWN: 'Please select at least one option',
}
